server {
    listen 80;
    server_name _;
    root  /usr/share/nginx/html;
    index index.html;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    resolver 127.0.0.11 valid=10s ipv6=off;

    location ~* \.(js|css|woff2|woff|ttf|svg|png|ico|webp)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    location ~* \.html$ {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location ~ ^/(uw-scales|auth|products|underwriting|queue|batch|tenants|users|letter-templates|health|rules|custom-rules|scales|physicians|reinsurance|notifications|reports|docs|redoc|openapi.json|premium-formula|physicians|members|gst-config|modal-factor-config|system) {
        set $backend http://fastapi:8000;
        proxy_pass         $backend;
        proxy_http_version 1.1;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   Authorization     $http_authorization;
        proxy_set_header   X-Forwarded-Method $request_method;
        proxy_read_timeout 120s;
        client_max_body_size 500M;
    }

    location / {
        try_files $uri $uri/ /index.html;
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}
